EXPERIMENT:
  NAME: "gerne"
  TAG: "sensitivity_bias_ratio_0_7"
  PROJECT: "chexpert_nih_sensitivity"
DATASET:
  TYPE: "chexpert_nih"
  BIASES: ["bias"]
  NUM_WORKERS: 0
  CHEXPERT_NIH:
    BIAS_RATIO: 0.7
MITIGATOR:
  TYPE: "gerne"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 20
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 0.0
  SCHEDULER:
    LR_DECAY_STAGES: [6, 13]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet18"
  PRETRAINED: True
METRIC: "wg_ovr"
