EXPERIMENT:
  NAME: "sd"
  TAG: "dev_in_out_scuba_swin"
  PROJECT: "ucf101_baselines"
DATASET:
  TYPE: "ucf101"
  BIASES: ["bias"]
  NUM_WORKERS: 0
MITIGATOR:
  TYPE: "sd"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 40
  LR: 0.001
  TYPE: "SGD"
  WEIGHT_DECAY: 1e-5
  SCHEDULER:
    LR_DECAY_STAGES: [20, 30]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "swin_t3d"
METRIC: "acc"
LOG:
  SAVE_CRITERION: "test"