EXPERIMENT:
  NAME: "end"
  TAG: "dev"
  PROJECT: "biased_mnist_baselines"
DATASET:
  TYPE: "biased_mnist"
  BIASES: ["color"]
MITIGATOR:
  TYPE: "end"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 80
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 0.0001
  SCHEDULER:
    LR_DECAY_STAGES: [26,53]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "simple_conv"
METRIC: "acc"
LOG:
  TRAIN_PERFORMANCE: True