EXPERIMENT:
  NAME: "jtt"
  TAG: "dev"
  PROJECT: "waterbirds_baselines"
DATASET:
  TYPE: "waterbirds"
  BIASES: ["background"]
MITIGATOR:
  TYPE: "jtt"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 300
  LR: 1e-5
  TYPE: "SGD"
  WEIGHT_DECAY: 1.0
  SCHEDULER:
    LR_DECAY_STAGES: [1000]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet50"
  PRETRAINED: True
METRIC: "wg_ovr_tags"
