EXPERIMENT:
  NAME: "bpa"
  TAG: "dev"
  PROJECT: "urbancars_baselines"
DATASET:
  TYPE: "urbancars"
  BIASES: ["bj_cooc_obj"]
MITIGATOR:
  TYPE: "bpa"
  BPA:
    CKPT_PATH: ""
    PER_CLUSTERS: 4
    UPDATE_CLUSTER_ITER: 10
    MOMENTUM: 0.3
    EXP_STEP: 0.05
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 150
  LR: 0.001
  TYPE: "SGD"
  WEIGHT_DECAY: 1e-4
  SCHEDULER:
    LR_DECAY_STAGES: [1000]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet50"
  PRETRAINED: True
METRIC: "wg_ovr"
