EXPERIMENT:
  NAME: "erm"
  TAG: "dev_in_out_scuba_swin"
  PROJECT: "ucf101_baselines"
DATASET:
  TYPE: "ucf101"
  BIASES: ["bias"]
  NUM_WORKERS: 0
MITIGATOR:
  TYPE: "erm"
SOLVER:
  BATCH_SIZE: 16
  EPOCHS: 30
  LR: 0.000125
  TYPE: "AdamW"
  WEIGHT_DECAY:  0.01
  SCHEDULER:
    TYPE: "cosine_with_warmup" 
    LINEAR_WARMUP: 2.5
MODEL:
  TYPE: "swin_t3d"
METRIC: "acc"
LOG:
  SAVE_CRITERION: "test"

