EXPERIMENT:
  NAME: "groupdro"
  TAG: "dev"
  PROJECT: "waterbirds_baselines"
DATASET:
  TYPE: "waterbirds"
  BIASES: ["background"]
MITIGATOR:
  TYPE: "groupdro"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 20
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 0.0
  SCHEDULER:
    LR_DECAY_STAGES: [60]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet50"
METRIC: "wg_ovr"
