EXPERIMENT:
  NAME: "sd"
  TAG: "dev"
  PROJECT: "imagenet9_baselines"
DATASET:
  TYPE: "imagenet9"
  BIASES: ["unknown"]
MITIGATOR:
  TYPE: "sd"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 40
  LR: 0.001
  TYPE: "SGD"
  WEIGHT_DECAY: 1e-4
  SCHEDULER:
    LR_DECAY_STAGES: [13, 26]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet50"
  PRETRAINED: True
METRIC: "wg_ovr_tags"


