EXPERIMENT:
  NAME: "george"
  TAG: "sensitivity_bias_ratio_0_7"
  PROJECT: "chexpert_nih_sensitivity"
DATASET:
  TYPE: "chexpert_nih"
  BIASES: ["bias"]
  NUM_WORKERS: 4
  CHEXPERT_NIH:
    BIAS_RATIO: 0.7
MITIGATOR:
  TYPE: "george"
  GEORGE:
    DISCOVERY_EPOCHS: 1
    CLUSTER_METHOD: "gmm"
    MAX_K: 10
    SEARCH_K: True
    REDUCTION: "umap"
    REDUCTION_COMPONENTS: 2
    ROBUST_STEP_SIZE: 0.01
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 20
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 0.0
  SCHEDULER:
    LR_DECAY_STAGES: [6, 13]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet18"
  PRETRAINED: True
METRIC: "wg_ovr"
