EXPERIMENT:
  NAME: "nsf"
  TAG: "blonde"
  PROJECT: "celeba_baselines"
DATASET:
  TYPE: "celeba"
  BIASES: ["gender"]
  CELEBA:
    BIAS: "gender"
    TARGET: "blonde"
MITIGATOR:
  TYPE: "nsf"
  NSF:
    CKPT_PATH: "./output/celeba_baselines/blonde/erm/best"
    FEATURE_SPLIT: "val"
    NUM_EPOCHS_TRANSFORM: 350
    NUM_EPOCHS_FT: 110
    LR_TRANSFORM: 0.001
    LR_FT: 0.001
    W_REG: 10.0
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 1
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 1e-4
  SCHEDULER:
    LR_DECAY_STAGES: [1000]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet18"
  PRETRAINED: True
  FREEZE_BACKBONE: False
METRIC: "wg_ovr"
