EXPERIMENT:
  NAME: "bpa"
  TAG: "sensitivity_bias_ratio_0_8"
  PROJECT: "chexpert_nih_sensitivity"
DATASET:
  TYPE: "chexpert_nih"
  BIASES: ["bias"]
  NUM_WORKERS: 4
  CHEXPERT_NIH:
    BIAS_RATIO: 0.8
MITIGATOR:
  TYPE: "bpa"
  BPA:
    CKPT_PATH: "./output/chexpert_nih_baselines/dev/erm/best"
    PER_CLUSTERS: 4
    UPDATE_CLUSTER_ITER: 10
    MOMENTUM: 0.3
    EXP_STEP: 0.05
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 20
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 0.0
  SCHEDULER:
    LR_DECAY_STAGES: [6, 13]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet18"
  PRETRAINED: True
METRIC: "wg_ovr"
