EXPERIMENT:
  NAME: "softcon"
  TAG: "dev"
  PROJECT: "waterbirds_baselines"
DATASET:
  TYPE: "waterbirds"
  BIASES: ["background"]
MITIGATOR:
  TYPE: "softcon"
  SOFTCON:
    BCC_PATH: "./output/waterbirds_baselines/tags/erm/best"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 20
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 0.0
  SCHEDULER:
    LR_DECAY_STAGES: [60]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet50"
  PRETRAINED: True
METRIC: "wg_ovr_tags"
