EXPERIMENT:
  NAME: "nsf"
  TAG: "dev_in_out_scuba_swin"
  PROJECT: "ucf101_baselines"
DATASET:
  TYPE: "ucf101"
  UCF101:
    TEST_BENCHMARK: "scuba"
    SAMPLE_DURATION: 32
  BIASES: ["bias"]
  NUM_WORKERS: 4
MITIGATOR:
  TYPE: "nsf"
  NSF:
    CKPT_PATH: "./output/ucf101_baselines/dev_in_out_scuba_swin/erm/best"
    FEATURE_SPLIT: "val"
    NUM_EPOCHS_TRANSFORM: 300
    NUM_EPOCHS_FT: 500
    LR_TRANSFORM: 0.001
    LR_FT: 0.001
    W_REG: 10.0
SOLVER:
  BATCH_SIZE: 16
  EPOCHS: 1
  LR: 0.0000125
  TYPE: "AdamW"
  WEIGHT_DECAY: 0.01
  SCHEDULER:
    TYPE: "cosine_with_warmup"
    LINEAR_WARMUP: 2.5
MODEL:
  TYPE: "swin_t3d"
METRIC: "acc"
LOG:
  SAVE_CRITERION: "test"
