EXPERIMENT:
  NAME: "di"
  TAG: "race"
  PROJECT: "utkface_baselines"
DATASET:
  TYPE: "utkface"
  BIASES: ["race"]
  UTKFACE:
    BIAS: "race"
MITIGATOR:
  TYPE: "di"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 20
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 0.0
  SCHEDULER:
    LR_DECAY_STAGES: [60]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet18"
METRIC: "unb_bc_ba"
