EXPERIMENT:
  NAME: "nsf"
  TAG: "dev"
  PROJECT: "urbancars_baselines"
DATASET:
  TYPE: "urbancars"
  BIASES: ["bj_cooc_obj"]
MITIGATOR:
  TYPE: "nsf"
  NSF:
    CKPT_PATH: ""
    FEATURE_SPLIT: "val"
    NUM_EPOCHS_TRANSFORM: 300
    NUM_EPOCHS_FT: 500
    LR_TRANSFORM: 0.001
    LR_FT: 0.001
    W_REG: 10.0
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 1
  LR: 0.001
  TYPE: "SGD"
  WEIGHT_DECAY: 1e-4
  SCHEDULER:
    LR_DECAY_STAGES: [1000]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet50"
  PRETRAINED: True
METRIC: "wg_ovr"
